### ISSUE TITLE
How to code jar file?

### ISSUE THREAD

**Issue by Hajiku68** [lilive/Freeplane-Jumper#22]
Hi, please tell me how to code jar file? 
I love your Freeplane addons, and I'm curious about the way you create them. 
I want to build my own jar files.
I studied [Freeplane API page](https://docs.freeplane.org/api/index.html), but it's too difficult for who is a newbie like me. 
Thanks,

**Comment by lilive** [comment]
Hi,

> I love your Freeplane addons

Thank you

> please tell me how to code jar file

Not sure about your question. I may be "how to compile a jar file for freeplane ?", but if you are a beginner I guess your question is more about "how to add some features to Freeplane with coding ?"
Am I right ?
If you are a beginner, no need to think about jar files. Start with regular scripts, there is a lot to do with them. See https://docs.freeplane.org/scripting/Start_Here.html. Only later, you may be want to create an addon from your scripts
If I am wrong an that your question is actually about how to compile a jar, you can have a look at the "Compilation from the sources" chapter of [the Jumper readme](https://github.com/lilive/Freeplane-Jumper).

**Comment by euu2021** [comment]
This may be helpful: https://github.com/freeplane/freeplane/discussions/374

**Comment by Hajiku68** [comment]
Thanks! After some days of research, I was able to build my own jar file and import it into my addon.
